version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: cival-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - cival-network

  dashboard:
    build: .
    container_name: cival-dashboard
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TRADING_API_URL=http://trading-api:3001
      - MCP_API_URL=http://mcp-server:3000
      - VAULT_API_URL=http://vault-service:3002
      
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@postgres:5432/trading}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      
      # Leverage Engine Configuration
      - ENABLE_LEVERAGE_ENGINE=true
      - MAX_LEVERAGE_RATIO=20
      - LEVERAGE_MARGIN_CALL_THRESHOLD=0.80
      - LEVERAGE_LIQUIDATION_THRESHOLD=0.95
      - ENABLE_AUTO_DELEVERAGING=true
      - LEVERAGE_RISK_MONITORING_INTERVAL=30000
      
      # Profit Securing Configuration
      - ENABLE_PROFIT_SECURING=true
      - PROFIT_SECURING_DEFAULT_PERCENTAGE=0.70
      - ENABLE_MILESTONE_AUTOMATION=true
      - DEFI_BORROW_PERCENTAGE=0.20
      - PROFIT_SECURING_MONITORING_INTERVAL=60000
      
      # DeFi Protocol Configuration
      - ENABLE_DEFI_PROTOCOLS=true
      - AAVE_V3_ENABLED=true
      - COMPOUND_V3_ENABLED=true
      - MAKERDAO_ENABLED=true
      - DEFI_HEALTH_FACTOR_THRESHOLD=2.0
      - DEFI_REBALANCE_THRESHOLD=1.5
      
      # Autonomous Coordination Configuration
      - ENABLE_AUTONOMOUS_COORDINATION=true
      - COORDINATOR_FREQUENCY_OPTIMIZATION=true
      - ADAPTIVE_MONITORING_ENABLED=true
      - COORDINATOR_LOW_ACTIVITY_MODE=true
      - COORDINATOR_HIGH_ACTIVITY_THRESHOLD=10
      
      # Enhanced Agent Configuration
      - ENABLE_ENHANCED_AGENT_CREATION=true
      - AGENT_LEVERAGE_INTEGRATION=true
      - AGENT_PROFIT_SECURING_INTEGRATION=true
      - AGENT_STATE_PERSISTENCE=true
      - AGENT_PERFORMANCE_TRACKING=true
    depends_on:
      - redis
      - trading-api
      - mcp-server
    networks:
      - cival-network

  trading-api:
    build:
      context: ./services/trading-api
    container_name: cival-trading-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/trading
    depends_on:
      - redis
      - postgres
    networks:
      - cival-network

  mcp-server:
    build:
      context: ./services/mcp-server
    container_name: cival-mcp-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - cival-network

  vault-service:
    build:
      context: ./services/vault-service
    container_name: cival-vault-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - VAULT_API_KEY=${VAULT_API_KEY}
    depends_on:
      - redis
    networks:
      - cival-network

  postgres:
    image: postgres:15
    container_name: cival-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=trading
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cival-network

  visualization-service:
    build:
      context: ./services/visualization
    container_name: cival-visualization
    ports:
      - "8002:8002"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - cival-network

networks:
  cival-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data: 