# Railway Configuration - Premium Trading Platform with 43+ Components
[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "always"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 30

[env]
NODE_ENV = "production"
PORT = "${PORT}"
NIXPACKS_NODE_VERSION = "18"

# Database Configuration
DATABASE_URL = "${DATABASE_URL}"
REDIS_URL = "${REDIS_URL}"
NEXT_PUBLIC_SUPABASE_URL = "${NEXT_PUBLIC_SUPABASE_URL}"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "${NEXT_PUBLIC_SUPABASE_ANON_KEY}"

# Persistence Configuration
ENABLE_AUTONOMOUS_PERSISTENCE = "true"
PERSISTENCE_AUTO_BACKUP = "true"
PERSISTENCE_BACKUP_INTERVAL = "60000"
PERSISTENCE_HEALTH_CHECK_INTERVAL = "30000"
PERSISTENCE_SYNC_INTERVAL = "5000"
PERSISTENCE_MAX_RETRIES = "3"
PERSISTENCE_COMPRESSION_ENABLED = "true"

# API Configuration
NEXT_PUBLIC_API_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
NEXT_PUBLIC_WS_URL = "wss://${RAILWAY_PUBLIC_DOMAIN}/ws"

# Premium Component Configuration
ENABLE_PREMIUM_FEATURES = "true"
ENABLE_ADVANCED_CHARTS = "true"
ENABLE_REALTIME_UPDATES = "true"
ENABLE_AGENT_ORCHESTRATION = "true"
ENABLE_RISK_MANAGEMENT = "true"
ENABLE_PORTFOLIO_ANALYTICS = "true"

# Trading Configuration
ENABLE_AUTONOMOUS_TRADING = "true"
AGENT_SCHEDULER_INTERVAL = "60000"
MAX_CONCURRENT_AGENTS = "20"
ENABLE_AUTO_REBALANCING = "true"
ENABLE_MULTI_EXCHANGE = "true"

# Performance Configuration
ENABLE_COMPONENT_CACHING = "true"
ENABLE_PERFORMANCE_MONITORING = "true"
CACHE_TTL_DEFAULT = "300"
ENABLE_COMPRESSION = "true"

# WebSocket Configuration
ENABLE_WEBSOCKET = "true"
WS_HEARTBEAT_INTERVAL = "30000"
WS_RECONNECT_INTERVAL = "5000"
WS_MAX_RECONNECT_ATTEMPTS = "10"

# Security Configuration
ENABLE_CORS = "true"
CORS_ORIGIN = "*"
ENABLE_RATE_LIMITING = "true"
RATE_LIMIT_MAX = "1000"

# Monitoring & Alerts
ENABLE_MONITORING = "true"
ALERT_WEBHOOK_URL = "${ALERT_WEBHOOK_URL}"
LOG_LEVEL = "info"
ENABLE_ERROR_TRACKING = "true"

# Leverage Engine Configuration
ENABLE_LEVERAGE_ENGINE = "true"
MAX_LEVERAGE_RATIO = "20"
LEVERAGE_MARGIN_CALL_THRESHOLD = "0.80"
LEVERAGE_LIQUIDATION_THRESHOLD = "0.95"
ENABLE_AUTO_DELEVERAGING = "true"
LEVERAGE_RISK_MONITORING_INTERVAL = "30000"

# Profit Securing Configuration
ENABLE_PROFIT_SECURING = "true"
PROFIT_SECURING_DEFAULT_PERCENTAGE = "0.70"
ENABLE_MILESTONE_AUTOMATION = "true"
DEFI_BORROW_PERCENTAGE = "0.20"
PROFIT_SECURING_MONITORING_INTERVAL = "60000"

# DeFi Protocol Configuration
ENABLE_DEFI_PROTOCOLS = "true"
AAVE_V3_ENABLED = "true"
COMPOUND_V3_ENABLED = "true"
MAKERDAO_ENABLED = "true"
DEFI_HEALTH_FACTOR_THRESHOLD = "2.0"
DEFI_REBALANCE_THRESHOLD = "1.5"

# Autonomous Coordination Configuration
ENABLE_AUTONOMOUS_COORDINATION = "true"
COORDINATOR_FREQUENCY_OPTIMIZATION = "true"
ADAPTIVE_MONITORING_ENABLED = "true"
COORDINATOR_LOW_ACTIVITY_MODE = "true"
COORDINATOR_HIGH_ACTIVITY_THRESHOLD = "10"

# Enhanced Agent Configuration
ENABLE_ENHANCED_AGENT_CREATION = "true"
AGENT_LEVERAGE_INTEGRATION = "true"
AGENT_PROFIT_SECURING_INTEGRATION = "true"
AGENT_STATE_PERSISTENCE = "true"
AGENT_PERFORMANCE_TRACKING = "true"

# Database Migration Configuration
AUTO_RUN_LEVERAGE_MIGRATION = "false"
ENABLE_DATABASE_HEALTH_CHECKS = "true"
DATABASE_MIGRATION_TIMEOUT = "300000"
ENABLE_TABLE_VERIFICATION = "true"

# Deployment Metadata
DEPLOYMENT_VERSION = "v100-leverage-profit-securing"
DEPLOYMENT_TIMESTAMP = "2025-07-12T00:00:00Z"
PREMIUM_COMPONENTS_COUNT = "43"
LEVERAGE_ENGINE_VERSION = "1.0.0"
PROFIT_SECURING_VERSION = "1.0.0"