# Railway Configuration - Premium Trading Platform with 43+ Components
[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "always"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 30

[env]
NODE_ENV = "production"
PORT = "${PORT}"
NIXPACKS_NODE_VERSION = "18"

# Database Configuration
DATABASE_URL = "${DATABASE_URL}"
REDIS_URL = "${REDIS_URL}"
NEXT_PUBLIC_SUPABASE_URL = "${NEXT_PUBLIC_SUPABASE_URL}"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "${NEXT_PUBLIC_SUPABASE_ANON_KEY}"

# API Configuration
NEXT_PUBLIC_API_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
NEXT_PUBLIC_WS_URL = "wss://${RAILWAY_PUBLIC_DOMAIN}/ws"

# Premium Component Configuration
ENABLE_PREMIUM_FEATURES = "true"
ENABLE_ADVANCED_CHARTS = "true"
ENABLE_REALTIME_UPDATES = "true"
ENABLE_AGENT_ORCHESTRATION = "true"
ENABLE_RISK_MANAGEMENT = "true"
ENABLE_PORTFOLIO_ANALYTICS = "true"

# Trading Configuration
ENABLE_AUTONOMOUS_TRADING = "true"
AGENT_SCHEDULER_INTERVAL = "60000"
MAX_CONCURRENT_AGENTS = "20"
ENABLE_AUTO_REBALANCING = "true"
ENABLE_MULTI_EXCHANGE = "true"

# Performance Configuration
ENABLE_COMPONENT_CACHING = "true"
ENABLE_PERFORMANCE_MONITORING = "true"
CACHE_TTL_DEFAULT = "300"
ENABLE_COMPRESSION = "true"

# WebSocket Configuration
ENABLE_WEBSOCKET = "true"
WS_HEARTBEAT_INTERVAL = "30000"
WS_RECONNECT_INTERVAL = "5000"
WS_MAX_RECONNECT_ATTEMPTS = "10"

# Security Configuration
ENABLE_CORS = "true"
CORS_ORIGIN = "*"
ENABLE_RATE_LIMITING = "true"
RATE_LIMIT_MAX = "1000"

# Monitoring & Alerts
ENABLE_MONITORING = "true"
ALERT_WEBHOOK_URL = "${ALERT_WEBHOOK_URL}"
LOG_LEVEL = "info"
ENABLE_ERROR_TRACKING = "true"

# Deployment Metadata
DEPLOYMENT_VERSION = "v95-premium"
DEPLOYMENT_TIMESTAMP = "2025-01-02T12:00:00Z"
PREMIUM_COMPONENTS_COUNT = "43"